[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo

# Configuración de red fija
proxy_mode = True
xmlrpc_port = 8069
gevent_port = 8072
limit_request = 8192
max_cron_threads = 1